/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SuccessLazyImport = createFileRoute('/success')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const StepsTributeDetailsLazyImport = createFileRoute('/steps/tributeDetails')()
const StepsPersonalDetailsLazyImport = createFileRoute(
  '/steps/personalDetails',
)()
const StepsPaymentDetailsLazyImport = createFileRoute('/steps/paymentDetails')()

// Create/Update Routes

const SuccessLazyRoute = SuccessLazyImport.update({
  path: '/success',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/success.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const StepsTributeDetailsLazyRoute = StepsTributeDetailsLazyImport.update({
  path: '/steps/tributeDetails',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/steps/tributeDetails.lazy').then((d) => d.Route),
)

const StepsPersonalDetailsLazyRoute = StepsPersonalDetailsLazyImport.update({
  path: '/steps/personalDetails',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/steps/personalDetails.lazy').then((d) => d.Route),
)

const StepsPaymentDetailsLazyRoute = StepsPaymentDetailsLazyImport.update({
  path: '/steps/paymentDetails',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/steps/paymentDetails.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/success': {
      preLoaderRoute: typeof SuccessLazyImport
      parentRoute: typeof rootRoute
    }
    '/steps/paymentDetails': {
      preLoaderRoute: typeof StepsPaymentDetailsLazyImport
      parentRoute: typeof rootRoute
    }
    '/steps/personalDetails': {
      preLoaderRoute: typeof StepsPersonalDetailsLazyImport
      parentRoute: typeof rootRoute
    }
    '/steps/tributeDetails': {
      preLoaderRoute: typeof StepsTributeDetailsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  SuccessLazyRoute,
  StepsPaymentDetailsLazyRoute,
  StepsPersonalDetailsLazyRoute,
  StepsTributeDetailsLazyRoute,
])

/* prettier-ignore-end */
